# **Tokenization**

In [107]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [108]:
# Sample Text

txt = "NLTK provide powerfull tools for tokenization. Its include word tokenization and sentence tokenization"

In [109]:
txt

'NLTK provide powerfull tools for tokenization. Its include word tokenization and sentence tokenization'

In [110]:
# Word tokenization
word_tokenize(txt)

['NLTK',
 'provide',
 'powerfull',
 'tools',
 'for',
 'tokenization',
 '.',
 'Its',
 'include',
 'word',
 'tokenization',
 'and',
 'sentence',
 'tokenization']

In [111]:
# Sentetence Tokenization
# It required .(dot) to split the sentence

sent_tokenize(txt)

['NLTK provide powerfull tools for tokenization.',
 'Its include word tokenization and sentence tokenization']

# **Stop Word Removal**

In [112]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [113]:
txt1= "Hello World. this is the sample text..."

In [114]:
# Case folding

txt1=txt1.lower()

In [115]:
txt1

'hello world. this is the sample text...'

In [116]:
# Filter out stop word

new_sentence = [word for word in word_tokenize(txt1) if word not in stopwords.words('english')]

In [117]:
new_sentence

['hello', 'world', '.', 'sample', 'text', '...']

In [118]:
# Check stop words list from the given sentence

stop_word_list = [word for word in word_tokenize(txt1) if word in stopwords.words('english')]
stop_word_list

['this', 'is', 'the']

# **Stemming & Lemmatization**

In [119]:
# Stemming
#  Stemming uses rigid rules to chop off word endings, which often leaves you with non-words (like happi)

import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [120]:
# Initialize the stemmer
stemmer = PorterStemmer()

In [121]:
# Sample Words

sample_words = ['running', 'runner', 'run', 'happiness','programming','bigger','biggest']

In [122]:
# Applying stemming technique

stemmer.stem(sample_words[1])

'runner'

In [123]:
# Converting all

for result in sample_words:
  print(stemmer.stem(result))

run
runner
run
happi
program
bigger
biggest

In [124]:
#Lemmatization
#Lemmatization uses a dictionary mapping to return a valid root word,
#transforming structural changes like plural to singular (mice to mouse) or past to present tense.

import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [125]:
sample_words_2 = ['geese','mice']

In [126]:
# initialize
lemm = WordNetLemmatizer()

In [127]:
lemm.lemmatize(sample_words_2[0])

'goose'

In [128]:
for i in sample_words_2:
  print(lemm.lemmatize(i))

goose
mouse

## **Bag of Words (BoW)** --> Vectorization

In [129]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [130]:
# Dataset Spam/ham
df = pd.read_csv("spam.csv")

In [131]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [132]:
df.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [133]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [134]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [135]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [136]:
# Converting ham as 0 and Spam as 1, adding as new column

df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [137]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

## **Train Test Split**

In [138]:
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.25)

In [139]:
len(X_test)

1393

In [140]:
X_train[:4]

1181                           I'm in chennai velachery:)
624     sorry, no, have got few things to do. may be i...
4765    Hi.:)technical support.providing assistance to...
924     She went to attend another two rounds today..b...
Name: Message, dtype: object

# Creating Bag of Words using countverctorization

In [141]:
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [142]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 55062 stored elements and shape (4179, 7454)>

In [143]:
# Just seeing in the array format of the X_train_cv, since its in integer format now

X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [144]:
v.vocabulary_ # count of words

#v.vocabulary_ maps each word to a unique column index in the feature matrix. For example,
#wrong: 7345 means the word wrong is represented by column 7345, not that it occurs 7,345 times.

{'in': 3511,
 'chennai': 1684,
 'velachery': 6999,
 'sorry': 6087,
 'no': 4609,
 'have': 3233,
 'got': 3081,
 'few': 2709,
 'things': 6592,
 'to': 6682,
 'do': 2274,
 'may': 4227,
 'be': 1195,
 'pub': 5271,
 'later': 3871,
 'hi': 3299,
 'technical': 6494,
 'support': 6373,
 'providing': 5259,
 'assistance': 1041,
 'us': 6950,
 'customer': 2035,
 'through': 6621,
 'call': 1529,
 'and': 897,
 'email': 2468,
 'she': 5836,
 'went': 7175,
 'attend': 1060,
 'another': 916,
 'two': 6830,
 'rounds': 5597,
 'today': 6689,
 'but': 1497,
 'still': 6241,
 'did': 2204,
 'reach': 5370,
 'home': 3345,
 'oh': 4716,
 'asked': 1033,
 'for': 2829,
 'fun': 2928,
 'haha': 3173,
 'take': 6441,
 'care': 1575,
 'that': 6559,
 'was': 7114,
 'forwarded': 2854,
 'message': 4282,
 'thought': 6611,
 'you': 7420,
 'send': 5772,
 'me': 4234,
 'says': 5692,
 'never': 4570,
 'answer': 919,
 'your': 7423,
 'texts': 6545,
 'confirm': 1869,
 'deny': 2159,
 'see': 5749,
 'the': 6562,
 'letter': 3927,
 'on': 4737,
 'my': 4484,
 'car': 1570,
 'yes': 7403,
 'fine': 2747,
 'noe': 4613,
 'how': 3389,
 'files': 2729,
 'between': 1256,
 'computers': 1852,
 'blank': 1306,
 'is': 3612,
 'wat': 7119,
 'lol': 4023,
 'haven': 3235,
 'lost': 4048,
 'ill': 3482,
 'always': 870,
 'here': 3286,
 '4u': 499,
 'didn': 2206,
 'intend': 3569,
 'hurt': 3429,
 'knew': 3806,
 'felt': 2704,
 'about': 705,
 'when': 7196,
 'iwas': 3636,
 'marine': 4189,
 'what': 7190,
 'itried2tell': 3628,
 'urmom': 6947,
 'careabout': 1576,
 'lmao': 3999,
 'nice': 4585,
 'look': 4032,
 'at': 1050,
 'fuckin': 2918,
 'time': 6649,
 'fuck': 2916,
 'think': 6593,
 'up': 6920,
 'natalja': 4514,
 '25': 348,
 'inviting': 3592,
 'her': 3285,
 'friend': 2894,
 'reply': 5490,
 '440': 463,
 'or': 4772,
 'www': 7352,
 'sms': 6024,
 'ac': 716,
 'nat27081980': 4513,
 'stop': 6253,
 'frnd': 2902,
 '62468': 540,
 'it': 3622,
 'ok': 4720,
 'least': 3898,
 'armand': 1001,
 'around': 1007,
 'this': 6600,
 'hex': 3294,
 'place': 5017,
 'talk': 6448,
 'of': 4697,
 'explain': 2616,
 'talking': 6451,
 'please': 5038,
 'dont': 2308,
 'forget': 2837,
 'pix': 5013,
 'want': 7103,
 'all': 847,
 'will': 7231,
 'gentle': 2993,
 'princess': 5198,
 'we': 7136,
 'make': 4158,
 'sweet': 6407,
 'love': 4062,
 'aathi': 695,
 'where': 7199,
 'are': 985,
 'dear': 2101,
 'pete': 4961,
 'can': 1552,
 'ring': 5558,
 'meive': 4260,
 'hardly': 3217,
 'gotany': 3082,
 'credit': 1974,
 'come': 1815,
 'back': 1125,
 'tampa': 6456,
 'ffffuuuuuuu': 2712,
 've': 6995,
 'bin': 1282,
 'awarded': 1099,
 '50': 503,
 'play': 5029,
 'instant': 3562,
 'cash': 1595,
 '08715203028': 123,
 'claim': 1737,
 'every': 2562,
 '9th': 687,
 'player': 5031,
 'wins': 7245,
 'min': 4309,
 '500': 504,
 'optout': 4771,
 '08718727870': 144,
 'challenge': 1638,
 'know': 3808,
 'am': 872,
 'hey': 3295,
 'booked': 1353,
 'pilates': 5002,
 'yoga': 7416,
 'lesson': 3923,
 'already': 860,
 'good': 3065,
 'afternon': 792,
 'hope': 3362,
 'maybe': 4229,
 'some': 6053,
 'interviews': 3579,
 'wake': 7084,
 'miss': 4337,
 'babe': 1117,
 'passionate': 4893,
 'kiss': 3798,
 'from': 2908,
 'across': 737,
 'sea': 5730,
 'cancel': 1556,
 'cheyyamo': 1689,
 'get': 3001,
 'money': 4395,
 'pick': 4989,
 'ur': 6936,
 'fone': 2817,
 'now': 4653,
 'dumb': 2380,
 'free': 2874,
 'activate': 743,
 'text': 6535,
 'messages': 4284,
 'by': 1512,
 'replying': 5491,
 'with': 7259,
 'word': 7305,
 'terms': 6522,
 'conditions': 1863,
 'visit': 7037,
 '07781482378': 30,
 'com': 1810,
 'da': 2051,
 'model': 4380,
 'num': 4662,
 'phone': 4975,
 'height': 3267,
 'confidence': 1867,
 'aeronautics': 778,
 'professors': 5228,
 'wer': 7177,
 'calld': 1534,
 'amp': 885,
 'they': 6586,
 'askd': 1032,
 'sit': 5949,
 'an': 892,
 'aeroplane': 779,
 'aftr': 795,
 'sat': 5674,
 'told': 6698,
 'dat': 2079,
 'plane': 5021,
 'ws': 7342,
 'made': 4137,
 'their': 6568,
 'students': 6295,
 'dey': 2191,
 'hurried': 3427,
 'out': 4800,
 'bt': 1459,
 'only': 4748,
 'didnt': 2207,
 'move': 4428,
 'he': 3244,
 'said': 5648,
 'if': 3471,
 'wont': 7296,
 'even': 2556,
 'start': 6206,
 'datz': 2086,
 'thanks': 6551,
 'ringtone': 5560,
 'order': 4778,
 'reference': 5430,
 't91': 6427,
 'charged': 1653,
 'gbp': 2978,
 'per': 4938,
 'week': 7156,
 'unsubscribe': 6915,
 'anytime': 939,
 'calling': 1541,
 'services': 5793,
 '09057039994': 169,
 'bout': 1375,
 '30ish': 406,
 'going': 3056,
 'as': 1022,
 'one': 4742,
 'our': 4799,
 'registered': 5446,
 'subscribers': 6319,
 'enter': 2506,
 'draw': 2337,
 '100': 245,
 'gift': 3013,
 'voucher': 7057,
 'actually': 748,
 'sleeping': 5978,
 'might': 4301,
 'so': 6042,
 'gr8': 3091,
 'rock': 5574,
 'sis': 5946,
 'wen': 7173,
 'jus': 3728,
 'its': 3629,
 'true': 6791,
 'missin': 4339,
 'cos': 1928,
 'really': 5388,
 'him': 3309,
 'done': 2306,
 'anything': 938,
 'feel': 2695,
 'guilty': 3155,
 'yet': 7406,
 'loving': 4072,
 'lor': 4042,
 'juz': 3734,
 'watched': 7121,
 'italian': 3623,
 'job': 3687,
 'landline': 3847,
 'number': 4663,
 'anna': 906,
 'nagar': 4494,
 'go': 3043,
 'afternoon': 793,
 'lt': 4085,
 'gt': 3140,
 'great': 3116,
 'loxahatchee': 4077,
 'xmas': 7361,
 'tree': 6777,
 'burning': 1486,
 'update': 6925,
 'totally': 6741,
 'stars': 6204,
 'win': 7234,
 'weekly': 7160,
 'professional': 5227,
 'sport': 6163,
 'does': 2286,
 'tiger': 6640,
 'woods': 7299,
 '87239': 646,
 'end': 2482,
 'service': 5792,
 'also': 863,
 'chat': 1664,
 'awesome': 1101,
 'don': 2305,
 'regular': 5449,
 'unless': 6903,
 'person': 4953,
 'shuhui': 5903,
 'has': 3222,
 'bought': 1374,
 'ron': 5586,
 'present': 5176,
 'swatch': 6402,
 'watch': 7120,
 'simply': 5932,
 'sitting': 5954,
 'watching': 7123,
 'match': 4206,
 'office': 4707,
 'im': 3486,
 'getting': 3007,
 'bad': 1128,
 'rejected': 5450,
 'kinda': 3793,
 'thing': 6591,
 'fyi': 2941,
 'usf': 6960,
 'swing': 6414,
 'room': 5587,
 'whenever': 7197,
 'eh': 2444,
 'remember': 5465,
 'spell': 6132,
 'his': 3315,
 'name': 4500,
 'naughty': 4521,
 'until': 6918,
 'wet': 7187,
 'give': 3025,
 'kvb': 3821,
 'acc': 717,
 'details': 2184,
 'not': 4641,
 'tonight': 6714,
 'mate': 4209,
 'catching': 1605,
 'sleep': 5976,
 'new': 4574,
 'way': 7131,
 'just': 3729,
 'gettin': 3006,
 'bit': 1292,
 'arty': 1019,
 'collages': 1798,
 'mo': 4367,
 'well': 7171,
 'tryin': 6799,
 'ne': 4528,
 'roast': 5571,
 'lovely': 4065,
 'shall': 5824,
 'enjoy': 2498,
 'half': 3181,
 'years': 7394,
 'missed': 4338,
 'friendship': 2896,
 'information': 3544,
 'ikea': 3479,
 'spelled': 6133,
 'caps': 1567,
 'yelling': 7396,
 'had': 3170,
 'left': 3906,
 'were': 7178,
 'bed': 1209,
 'among': 881,
 'mess': 4281,
 'came': 1547,
 'after': 791,
 'class': 1743,
 'try': 6798,
 'bullshit': 1476,
 'makes': 4159,
 'listen': 3983,
 'less': 3921,
 'spend': 6135,
 'days': 2089,
 'waiting': 7083,
 'ideal': 3461,
 'path': 4899,
 'appear': 956,
 'front': 2910,
 'paths': 4901,
 'walking': 7092,
 'goodnight': 3070,
 'wow': 7326,
 're': 5369,
 'right': 5552,
 'mean': 4237,
 'guess': 3148,
 'once': 4740,
 'gave': 2973,
 'boston': 1368,
 'men': 4271,
 'changed': 1644,
 'search': 5731,
 'location': 4008,
 'nyc': 4677,
 'something': 6062,
 'cuz': 2046,
 'signin': 5920,
 'page': 4838,
 'should': 5880,
 'change': 1643,
 'fb': 2686,
 'jaykwon': 3661,
 'thuglyfe': 6629,
 'falconerf': 2650,
 'tell': 6504,
 'whos': 7213,
 'pls': 5046,
 'being': 1228,
 'baby': 1120,
 'who': 7209,
 'spent': 6137,
 'last': 3865,
 'night': 4592,
 'phasing': 4967,
 'fourth': 2858,
 'dimension': 2225,
 'heart': 3257,
 'empty': 2480,
 'without': 7263,
 'mind': 4312,
 'wisdom': 7249,
 'eyes': 2630,
 'dreams': 2341,
 'life': 3940,
 'frnds': 2903,
 'alwys': 871,
 'touch': 6743,
 'hello': 3273,
 'news': 4579,
 'making': 4161,
 'wait': 7080,
 'fifth': 2720,
 'yeah': 7392,
 'woozles': 7303,
 'weasels': 7143,
 'exeter': 2597,
 'steve': 6234,
 'morning': 4414,
 'successful': 6327,
 'day': 2088,
 'leh': 3912,
 'tuition': 6812,
 'looking': 4035,
 'slots': 5992,
 'driving': 2354,
 'lessons': 3924,
 'alright': 861,
 'omw': 4736,
 'gotta': 3085,
 'half8th': 3182,
 'won': 7289,
 'guaranteed': 3143,
 '1000': 246,
 '2000': 329,
 'prize': 5208,
 'yr': 7432,
 'representative': 5495,
 'popped': 5099,
 'ask': 1031,
 'been': 1213,
 'tonght': 6712,
 'girl': 3019,
 'comes': 1817,
 'pouch': 5128,
 'hungry': 3421,
 'buy': 1502,
 'smth': 6028,
 'wot': 7321,
 'wanna': 7101,
 'then': 6574,
 'missy': 4345,
 'coming': 1821,
 'funeral': 2931,
 'oooh': 4753,
 'ridden': 5550,
 'ey': 2627,
 'thinking': 6596,
 'wine': 7240,
 'flowing': 2799,
 'nevering': 4571,
 'fast': 2671,
 'lose': 4043,
 'weight': 7164,
 'thk': 6601,
 'muz': 4481,
 'month': 4403,
 'den': 2152,
 'effect': 2435,
 'gee': 2983,
 'aust': 1077,
 'put': 5293,
 'bk': 1299,
 'msg': 4440,
 'why': 7216,
 'nothing': 4646,
 'anyway': 940,
 'treat': 6775,
 'excuse': 2593,
 'city': 1734,
 'year': 7393,
 'though': 6610,
 'very': 7006,
 'team': 6488,
 'like': 3950,
 'india': 3531,
 'ready': 5379,
 'moan': 4368,
 'scream': 5719,
 'internet': 3577,
 'connection': 1880,
 'slow': 5994,
 'again': 797,
 'first': 2761,
 'tomo': 6705,
 'annoying': 913,
 'isn': 3618,
 'people': 4936,
 'dearer': 2103,
 'de': 2095,
 'happiness': 3211,
 'meet': 4252,
 'them': 6570,
 'pain': 4842,
 'dem': 2150,
 'tot': 6739,
 'liao': 3932,
 'shirt': 5854,
 'sunshine': 6365,
 'quiz': 5319,
 'wkly': 7273,
 'top': 6727,
 'sony': 6075,
 'dvd': 2391,
 'which': 7203,
 'country': 1945,
 'algarve': 841,
 'txt': 6832,
 'ansr': 918,
 '82277': 612,
 'sp': 6105,
 'tyrone': 6848,
 'darlin': 2075,
 'wish': 7251,
 'cant': 1562,
 'fran': 2865,
 'ps': 5263,
 'dirty': 2242,
 'anal': 894,
 'sex': 5805,
 '10': 244,
 'man': 4167,
 'gang': 2959,
 'bang': 1145,
 'dad': 2054,
 'lar': 3860,
 'wan': 7098,
 'stay': 6218,
 'meh': 4258,
 'holy': 3344,
 'living': 3994,
 'christ': 1723,
 'taking': 6446,
 'long': 4029,
 'normally': 4635,
 'hot': 3379,
 'mail': 4151,
 'wun': 7351,
 'signing': 5921,
 'tmr': 6676,
 'hee': 3265,
 'need': 4540,
 'nitros': 4605,
 'hurry': 3428,
 'before': 1218,
 'crash': 1963,
 'show': 5887,
 'colours': 1809,
 'euro': 2550,
 '2004': 331,
 'offer': 4703,
 'england': 2496,
 'flag': 2774,
 '3lions': 434,
 'tone': 6708,
 'click': 1757,
 'following': 2813,
 'info': 3542,
 'probably': 5214,
 'over': 4814,
 'stuff': 6299,
 'shhhhh': 5846,
 'nobody': 4612,
 'supposed': 6376,
 'xxxmobilemovieclub': 7369,
 'use': 6954,
 'wap': 7108,
 'link': 3970,
 'next': 4583,
 'http': 3404,
 'qjkgighjjgcbl': 5302,
 'others': 4794,
 'marry': 4196,
 'picking': 4991,
 'various': 6987,
 'points': 5075,
 'waste': 7117,
 'rr': 5604,
 'lovin': 4071,
 'vl': 7043,
 'bcum': 1191,
 'more': 4410,
 'difficult': 2217,
 'much': 4455,
 'hdd': 3243,
 'casing': 1599,
 'cost': 1930,
 'gets': 3004,
 'twelve': 6823,
 'aah': 693,
 'speak': 6117,
 'cheers': 1681,
 'callin': 1540,
 'sozi': 6104,
 'culdnt': 2019,
 'talkbut': 6449,
 'wannatell': 7102,
 'wenwecan': 7176,
 'properly': 5247,
 'thts': 6628,
 'wright': 7330,
 'brother': 1446,
 'fly': 2804,
 'opinion': 4762,
 'jada': 3644,
 'kusruthi': 3820,
 'lovable': 4061,
 'silent': 5924,
 'spl': 6146,
 'character': 1650,
 'matured': 4220,
 'stylish': 6308,
 'simple': 5930,
 'book': 1352,
 'chez': 1690,
 'jules': 3719,
 'eight': 2446,
 'custom': 2034,
 'officer': 4708,
 'discount': 2252,
 'online': 4746,
 'let': 3925,
 'pa': 4831,
 'knw': 3812,
 'ru': 5611,
 'guy': 3159,
 'used': 6955,
 'too': 6718,
 'realize': 5386,
 'gimme': 3017,
 'minutes': 4327,
 'ago': 806,
 'set': 5796,
 'sir': 5945,
 'axis': 1105,
 'bank': 1147,
 'account': 728,
 'address': 757,
 'spatula': 6116,
 'hands': 3192,
 'dun': 2382,
 'wear': 7140,
 'jeans': 3666,
 'awake': 1097,
 'refused': 5439,
 'loan': 4004,
 'secured': 5747,
 'unsecured': 6911,
 '0800': 47,
 '195': 311,
 '6669': 546,
 'help': 3275,
 'hear': 3254,
 'joke': 3698,
 'thet': 6584,
 'skinny': 5963,
 'white': 7207,
 'girls': 3022,
 'other': 4793,
 'line': 3964,
 'camera': 1548,
 'casting': 1600,
 'sentence': 5782,
 'into': 3581,
 'because': 1204,
 'concentrate': 1855,
 'educational': 2430,
 'career': 1578,
 'leaving': 3902,
 'plans': 5026,
 'family': 2657,
 'stone': 6250,
 'especially': 2541,
 'since': 5934,
 'personal': 4955,
 'statement': 6214,
 'woulda': 7324,
 'realized': 5387,
 'plz': 5051,
 'note': 4642,
 'anyone': 934,
 'mobile': 4371,
 'co': 1781,
 'asks': 1036,
 'type': 6845,
 'disconnect': 2250,
 'coz': 1954,
 'iz': 3638,
 'attempt': 1058,
 'terrorist': 6527,
 'sim': 5928,
 'card': 1571,
 'itz': 3632,
 'confirmd': 1870,
 'nokia': 4617,
 'motorola': 4424,
 'verified': 7002,
 'cnn': 1779,
 'ibn': 3448,
 'spoke': 6156,
 'maneesha': 4175,
 'satisfied': 5677,
 'experience': 2610,
 'toll': 6702,
 'workin': 7309,
 'oso': 4792,
 'thgt': 6588,
 'fren': 2885,
 'shop': 5867,
 'hook': 3358,
 'means': 4241,
 'tried': 6781,
 'contact': 1891,
 'video': 7014,
 '750': 576,
 'any': 930,
 'network': 4565,
 'mins': 4323,
 'price': 5193,
 'rental': 5479,
 'camcorder': 1546,
 '08000930705': 51,
 'private': 5205,
 '2003': 330,
 'shows': 5894,
 '800': 592,
 'un': 6867,
 'redeemed': 5426,
 '08718738002': 149,
 'identifier': 3464,
 'code': 1789,
 '48922': 479,
 'expires': 2614,
 '21': 339,
 '11': 258,
 '04': 14,
 'tht': 6627,
 'hoping': 3368,
 'enjoyed': 2499,
 'game': 2955,
 'yesterday': 7405,
 'fondly': 2816,
 'bein': 1227,
 'thot': 6608,
 'off': 4699,
 'abiola': 701,
 'chance': 1641,
 '150': 289,
 'worth': 7320,
 'vouchers': 7058,
 '85023': 629,
 'savamob': 5682,
 'member': 4265,
 'offers': 4706,
 'cs': 1998,
 '08717898035': 137,
 '00': 0,
 'sub': 6309,
 '16': 302,
 'remove': 5473,
 'hostel': 3377,
 'hrishi': 3400,
 'quite': 5316,
 '1mega': 316,
 'pixels': 5014,
 '3optical': 439,
 '5digital': 520,
 'dooms': 2311,
 'holiday': 3340,
 'safe': 5644,
 'hav': 3231,
 'journey': 3709,
 'happy': 3212,
 'both': 1370,
 'couple': 1947,
 'weeks': 7161,
 'write': 7331,
 'dictionary': 2203,
 'mode': 4379,
 'cover': 1951,
 'screen': 5722,
 'hand': 3189,
 'press': 5180,
 'gently': 2995,
 'interesting': 3573,
 'wining': 7242,
 '946': 676,
 'collect': 1800,
 'lei': 3913,
 'yup': 7440,
 'studying': 6298,
 'surfing': 6382,
 'lazy': 3885,
 'needs': 4545,
 'fucking': 2919,
 'dealing': 2099,
 'll': 3996,
 'close': 1763,
 'sipix': 5943,
 'digital': 2220,
 '09061221066': 186,
 'fromm': 2909,
 'delivery': 2147,
 'within': 7262,
 '28': 356,
 'having': 3239,
 'movies': 4432,
 'laptop': 3859,
 'engin': 2495,
 'arts': 1018,
 'inconvenient': 3524,
 'huh': 3414,
 'seems': 5756,
 'unnecessarily': 6907,
 'affectionate': 783,
 '08712400200': 102,
 'lick': 3935,
 'pussy': 5292,
 'heard': 3255,
 'wildlife': 7230,
 'want2come': 7104,
 'that2worzels': 6560,
 'wizzle': 7268,
 'whatever': 7191,
 'valued': 6982,
 'pleased': 5039,
 'advise': 776,
 'recent': 5407,
 'review': 5540,
 'mob': 4369,
 '1500': 290,
 'bonus': 1350,
 '09066364589': 224,
 'boo': 1351,
 'enjoyin': 2500,
 'yourjob': 7425,
 'seemed': 5755,
 'hunny': 3423,
 'ure': 6938,
 'llspeak': 3998,
 '2u': 391,
 'soonlots': 6080,
 'loveme': 4066,
 'xxxx': 7370,
 'fudge': 2920,
 'oreos': 4783,
 'stores': 6263,
 'urgent': 6940,
 'important': 3502,
 'o2': 4682,
 'user': 6958,
 'lucky': 4092,
 'find': 2744,
 'log': 4015,
 'onto': 4751,
 'urawinner': 6937,
 'there': 6578,
 'fantastic': 2665,
 'surprise': 6386,
 'awaiting': 1096,
 'dhoni': 2194,
 'luck': 4090,
 'big': 1271,
 'title': 6663,
 'fact': 2636,
 'needed': 4542,
 'hour': 3383,
 'chase': 1661,
 'run': 5624,
 'while': 7204,
 'crossing': 1988,
 'street': 6274,
 'okay': 4721,
 'ah': 808,
 'drop': 2357,
 'cards': 1574,
 'box': 1379,
 'monday': 4393,
 'feeling': 2697,
 'dentists': 2158,
 'sure': 6380,
 'parents': 4872,
 'working': 7310,
 'tuesday': 6810,
 'story': 6266,
 'neva': 4568,
 'worry': 7317,
 'truth': 6797,
 'lead': 3892,
 'unique': 6897,
 'deserve': 2174,
 'tight': 6641,
 'sun': 6358,
 'fancy': 2662,
 'drink': 2346,
 'luton': 4100,
 '0125698789': 7,
 'themob': 6573,
 'check': 1674,
 'newest': 4576,
 'selection': 5761,
 'content': 1895,
 'games': 2956,
 'tones': 6709,
 'gossip': 3080,
 'babes': 1118,
 'keep': 3762,
 'fit': 2765,
 'funky': 2933,
 '82468': 614,
 'meeting': 4254,
 'ge': 2982,
 'nite': 4603,
 'goodmorning': 3069,
 'late': 3868,
 'anthony': 927,
 'bf': 1261,
 ...}

In [145]:
X_train_np = X_train_cv.toarray()
X_train_np[0]
np.where(X_train_np[0]!=0)

(array([1684, 3511, 6999]),)

# **ML Model**

In [146]:
# Using DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train_cv, y_train)

DecisionTreeClassifier()

In [149]:
y_pred = model.predict(X_test_cv)

In [158]:
# Printing Classification Report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1181
           1       0.94      0.85      0.89       212

    accuracy                           0.97      1393
   macro avg       0.96      0.92      0.94      1393
weighted avg       0.97      0.97      0.97      1393

In [160]:
# Need to verify accurecy score

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

96.8413496051687

## **Test on Random Datapoint**

In [172]:
message1 = {"Wow... You won iPhone 16 Plus, click the below-link to claim"}
message2 = {"Please join the meeting tomorrow morning, without fail5"}

In [173]:
# Transformning the above message

message_cnt = v.transform(message1)
message_cnt1 = v.transform(message2)
model.predict(message_cnt)

array([1])

In [174]:
model.predict(message_cnt1)

array([0])

# **TF-IDF**

In [175]:
from sklearn.feature_extraction.text import TfidfVectorizer

v = TfidfVectorizer()

X_train_cv = v.fit_transform(X_train)
X_test_cv = v.transform(X_test)

model.fit(X_train_cv, y_train)

DecisionTreeClassifier()

In [176]:
y_pred1 = model.predict(X_test_cv)

In [178]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1181
           1       0.93      0.78      0.85       212

    accuracy                           0.96      1393
   macro avg       0.95      0.88      0.91      1393
weighted avg       0.96      0.96      0.96      1393

In [179]:
# Need to verify accurecy score

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)*100

95.76453697056712

In [180]:
# Transformning the above message

message_cnt = v.transform(message1)
message_cnt1 = v.transform(message2)
model.predict(message_cnt)

array([1])